### ISSUE TITLE
Prepare Kibana Chart for integration into 'logging' Helm Chart

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/chart-kibana#2]
Test with current iteration of "logging" chart
Integrate Kibana as dependency when functioning correctly

**Comment by leahnp** [comment]
<img width="1371" alt="screen shot 2017-10-13 at 5 18 02 pm" src="https://user-images.githubusercontent.com/13352646/31566938-e3a66fa0-b03a-11e7-9b24-611e286bf1e5.png">
We've got logs!

I got these by deploying the following charts: fluent-bit, elasticsearch-chart, kibana-chart.

Looks like everything is ready for the official 'logging' chart.


To review - deploy these 3 charts, go to the kibana elb and see if you find the logs!

**Comment by DStorck** [comment]
Works for me.
