### ISSUE TITLE
Remove "latest" tag from Quay image

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/chart-kibana#3]
*Currently waiting for jenkins plugin to allow tagging quay images (with something other than 'latest')
Add a versioned tag

**Comment by coffeepac** [comment]
manually push a tag to github and quay and update the chart.

**Comment by coffeepac** [comment]
labels: blocked, p1, etc

**Comment by coffeepac** [comment]
this should be done in gitlab CI.  system is ready for building against.

**Comment by guineveresaenger** [comment]
this is still blocked, but not for long
